version: '3.8'
services:
  postgres:
    container_name: gold_price_tracker_db
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postresql/data
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gold_price_tracker
  # api:
  #   container_name: gold_price_tracker_api
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.local
  #   ports:
  #     - '3008:3008'
volumes:
  dbdata:
    name: gold_price_tracker_db_volume
