name: Test and deploy

on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    needs: [test]
    if: ${{ needs.test.result == 'success'  }}
